// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu5GKRLYJclDJAEmDP-KvOedSIOZU0yuo',
    appId: '1:440663622686:web:367661d6fedee65b851a0f',
    messagingSenderId: '440663622686',
    projectId: 'emergencyapp-807bf',
    authDomain: 'emergencyapp-807bf.firebaseapp.com',
    storageBucket: 'emergencyapp-807bf.firebasestorage.app',
    measurementId: 'G-RF5MD97E0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoTK-2-1bWTzTXAEO5x4uJdMghS2qGp8I',
    appId: '1:440663622686:android:4dd5eb6c692f06c0851a0f',
    messagingSenderId: '440663622686',
    projectId: 'emergencyapp-807bf',
    storageBucket: 'emergencyapp-807bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5DI1X79ANZoIjfYkUBPYWwX0DdKy2AoA',
    appId: '1:440663622686:ios:f3763a496b928e8b851a0f',
    messagingSenderId: '440663622686',
    projectId: 'emergencyapp-807bf',
    storageBucket: 'emergencyapp-807bf.firebasestorage.app',
    iosBundleId: 'com.example.emergencyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5DI1X79ANZoIjfYkUBPYWwX0DdKy2AoA',
    appId: '1:440663622686:ios:f3763a496b928e8b851a0f',
    messagingSenderId: '440663622686',
    projectId: 'emergencyapp-807bf',
    storageBucket: 'emergencyapp-807bf.firebasestorage.app',
    iosBundleId: 'com.example.emergencyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu5GKRLYJclDJAEmDP-KvOedSIOZU0yuo',
    appId: '1:440663622686:web:e3c32cfe321f363d851a0f',
    messagingSenderId: '440663622686',
    projectId: 'emergencyapp-807bf',
    authDomain: 'emergencyapp-807bf.firebaseapp.com',
    storageBucket: 'emergencyapp-807bf.firebasestorage.app',
    measurementId: 'G-2VH1JZXC78',
  );
}
